### ISSUE TITLE
ARPA SPENDING Pre-publication Checklist

### ISSUE THREAD

**Issue by Weihua4455** [themarshallproject/arpa20220125#39]
With David going on vacation next week, I laid out a list of things we have to wrap up by Friday, and things that we can figure out next out without David.

Things to wrap up by Friday:

- [x] Finish and copy-edit story draft
- [ ] Headline and deck
- [x] Randousel (the name is here to stay)
- [x] Turn off Airtable fetching
- [x] Art (?)
- [x] Finish building Data Wrapper charts

Things that we might have to wrap up next week:

- [x] Partnership with Axios
- [ ] Data Wrapper styles
- [x] Production

Lmk how this list looks to you! Happy to make adjustments or move things around. @anastasiajourno @susie-c @eads

**Comment by Weihua4455** [comment]
I went through the story draft this morning. Love how much information we managed to pack in there, and kudos to @anastasiajourno for getting a lot of amazing voices.

The only parts that I think are missing are 1) adding Independence in the CVI section and 2) think more about the ending/if we should do a call out.

@anastasiajourno would you like to take the Independence, MO part? Would love feedback from @eads @susie-c & perhaps we can brainstorm about the ending more.

**Comment by Weihua4455** [comment]
From @eads this morning:

Main story:

- [ ] Datawrapper is going nicely, we should have TMP styles available by tomorrow.
- [ ] Axios finally reappeared and can meet tomorrow, so I'm doing that. Since this is the biggest dependency for publishing next week, I'm going to sync up [@susie](https://themarshallproject.slack.com/team/U02RD35PG) with [@Terri Troncale (she/her)](https://themarshallproject.slack.com/team/UNTQCN084) and co.
- [ ] I've instructed [@Weihua (she/her/hers)](https://themarshallproject.slack.com/team/UKXR4UQCW) to keep it loose next week to help get this out the door; that will definitely involve doing production but also coordinating data with Axios.

Independence folo:

- [ ] Anastasia is picking up graphics for SHERIFFSURVEY while I'm out. That's slippery -- if it slips on the sooner side, we'll need to hold off on Independence; it could also totally go the other way and we'll want to start on Independence.
- [ ] I'm asking [@Terri Troncale (she/her)](https://themarshallproject.slack.com/team/UNTQCN084) and Ruth to help with Independence. Ebony Reed has interest as well, but she's biz side. In all events, I think working with the partnerships team next week is probably the most important thing to move Independence fwd, maybe even more than drafting something immediately.

**Comment by susie-c** [comment]
Draft checklist!

- [ ] Lede: add a brief sum-up about how ARPA reflects local municipal priorities and values, instead of imposing clear priorities and limits, let alone regulatory oversight
- [ ] Chart text: needs a snappy/accurate headline
- [ ] Staffing: Tighten up the Pembroke section just a little!
- [ ] CVI: Add sum of this category spending
- [ ] CVI: Add one or two more examples -- this section is a little slim compared to others, could use some beef.
- [ ] Courts: Ana, look over my edits!
- [ ] A general consistency note through the copy: Are we thinking of the ARPA budgeting as past or present tense? We switch back and forth at times. Are cities allocating or have they already allocated? I know this is tricky because it's all in flux! But we should land on one or the other.

**Comment by Weihua4455** [comment]
Re past or present tense: English is so hard!! I think present tense, since some of the projects are on-going? But I might not be the best person to answer this.
