### ISSUE TITLE
Datawrapper todo

### ISSUE THREAD

**Issue by anastasiajourno** [themarshallproject/arpa20220125#72]
- [x] fix the font for numeric values 
- [x] figure out the 'obligations' header
- [x] figure out the asterisks

**Comment by katiepark** [comment]
Thinking through the "obligations" stuff -- I think "amount allocated" feels like a reasonable replacement for "obligation." I know it gets a little iffy with the difference between "obligation" and "adopted budget," but I definitely don't think the distinction will matter to the reader, and we use "allocated" elsewhere in the piece.

My other thought was "projects funded," but that doesn't actually refer to dollar amounts.... "Amount funded" might work but doesn't feel as clear as "Amount allocated."

**Comment by katiepark** [comment]
Right now the first asterisk really means nothing to me. (` * Refers to the group "Public health-negative economic impact: public sector capacity." `)

You know the data way better than I do, so let me know if I have this right. "Public health-negative economic impact: public sector capacity" is a category of projects that increase public sector capacity, which may include—but is not limited to—jobs in public health. If I'm understanding this correctly, then I think it would be clearer to keep the "Public sector capacity" category name and have an asterisk that says "* Includes some public health projects"

The point you're trying to make is that public health is not the #1 priority in ARPA spending, but we also don't want to be misleading by not indicating that "public sector capacity" does support public health staffing. So the key thing here is indicating that this tiny amount of funding does cover public health to some extent. It isn't necessary for us to use all the Treasury wording verbatim if we're communicating the same point accurately.

**Comment by anastasiajourno** [comment]
Thank you. How about 'Refers to public health'? 
It should all be public health-related, not some... 

Yes, I think the struggle here was the balance between preserving the Treasury naming and clarity... 
I was not sure how far we can go.

**Comment by katiepark** [comment]
Is that true, though, that "public sector capacity" refers entirely to public health staffing? I wasn't sure of the best place to look at the source material but I was looking at [this document](https://www.federalregister.gov/d/2022-00292/p-744) to try to make sense of it:

>Public Sector Capacity and Workforce, which includes several separate and non-mutually exclusive categories articulated in the interim final rule: public health and safety staff; rehiring state, local, and Tribal government staff; expenses for administering COVID-19 response programs; expenses to improve the efficacy of public health or economic relief programs; and administrative expenses caused or exacerbated by the pandemic. Treasury recognizes that these are closely related and frequently overlapping categories. The final rule treats them as a single purpose, supporting public sector capacity, and provides coordinated guidance on the standards and presumptions that apply to them.

Based on this, it seems like the category also includes economic relief and other programs that generally support the public sector workforce.

**Comment by anastasiajourno** [comment]
It should be https://home.treasury.gov/system/files/136/SLFRF-Compliance-and-Reporting-Guidance.pdf 
page 44
But yes, thank you, you are right! I corrected for 'includes public health projects'
